/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'huyluu' at '12/5/16 10:41 AM' with Gradle 3.2
 *
 * @author huyluu, @date 12/5/16 10:41 AM
 */
public class Pixabay {

}
