import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'huyluu' at '12/5/16 10:41 AM' with Gradle 3.2
 *
 * @author huyluu, @date 12/5/16 10:41 AM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Pixabay classUnderTest = new Pixabay();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
