import com.unikre.pixabay.PixabayCallback;
import com.unikre.pixabay.PixabayClient;
import com.unikre.pixabay.http.Image;
import com.unikre.pixabay.http.Result;
import com.unikre.pixabay.http.Video;
import org.junit.Assert;
import org.junit.Test;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'huyluu' at '12/5/16 10:41 AM' with Gradle 3.2
 *
 * @author huyluu, @date 12/5/16 10:41 AM
 */
public class PixabayTest {
    public static final String KEY = "3924820-487f730fa926b2e0aa9bfec4b";
    public static final PixabayClient pixabay = new PixabayClient(KEY);
    private CountDownLatch lock = new CountDownLatch(1);

    @Test
    public void testSimpleSearch() throws Exception {
        Result<Image> imageResponse = pixabay.searchImage("flowers");
        Assert.assertNotNull(imageResponse);

        Result<Video> videoResponse = pixabay.searchVideo("flowers");
        Assert.assertNotNull(videoResponse);
    }

    @Test
    public void testAsyncSearch() throws Exception {
        pixabay.searchImage("book", new PixabayCallback<Result<Image>>() {
            @Override
            public void onResponse(Result<Image> result) {
                Assert.assertNotNull(result);
                lock.countDown();
            }

            @Override
            public void onFailure(Throwable t) {
                t.printStackTrace();
            }
        });
        lock.await(2000, TimeUnit.MILLISECONDS);
    }
}
