import com.unikre.pixabay.PixabayClient;
import com.unikre.pixabay.http.Image;
import com.unikre.pixabay.http.Response;
import com.unikre.pixabay.http.Video;
import org.junit.Assert;
import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'huyluu' at '12/5/16 10:41 AM' with Gradle 3.2
 *
 * @author huyluu, @date 12/5/16 10:41 AM
 */
public class PixabayTest {
    public static final String KEY = "3924820-487f730fa926b2e0aa9bfec4b";
    public static final PixabayClient pixabay = new PixabayClient(KEY);

    @Test
    public void testSimpleSearch() throws Exception {
        Response<Image> imageResponse = pixabay.searchImage("flowers");
        Assert.assertNotNull(imageResponse);

        Response<Video> videoResponse = pixabay.searchVideo("flowers");
        Assert.assertNotNull(videoResponse);
    }
}
